# options for analysis running
run:
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - hack
    - docs

linters:
  enable:
    - gocritic
    - goimports
    - golint
    - gosimple
    - interfacer
    - maligned
    - misspell
    - unconvert
    - unparam
    - stylecheck
    - staticcheck
    - structcheck
    - prealloc
  disable:
    - errcheck
