name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Prepare environment
      run: |
        pwd
        echo $GOPATH
        echo $PATH
        go env
        go mod download
        hack/install-gox.sh\
      env:
        GOPATH: /home/runner/work/krew/go
        GOBIN: /home/runner/work/krew/go/bin
        PATH: $PATH:/home/runner/work/krew/go/bin

    - name: Install dependencies
      run: |
        go mod tidy && git diff --no-patch --exit-code
        hack/verify-code-patterns.sh
        hack/verify-boilerplate.sh
        hack/run-lint.sh
        go test -short -coverprofile=coverage.txt -covermode=atomic ./...
        hack/make-all.sh
        hack/verify-installation.sh
        hack/ensure-kubectl-installed.sh
        hack/run-integration-tests.sh
        hack/verify-receipts-upgrade-migration.sh

    - name: Build
      run: go build -v .
