name: Push or PR
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
    
    - name: Prepare environment
      run: |
        go mod download
        hack/install-gox.sh\

    - name: Install dependencies
      run: |
        go mod tidy && git diff --no-patch --exit-code
        hack/verify-code-patterns.sh
        hack/verify-boilerplate.sh
        hack/run-lint.sh
        go test -short -coverprofile=coverage.txt -covermode=atomic ./...
        hack/make-all.sh
        hack/verify-installation.sh
        hack/ensure-kubectl-installed.sh
        hack/run-integration-tests.sh
        hack/verify-receipts-upgrade-migration.sh
